let name = "Erwin Henraat";
console.log("Name: " + name);
let jumpforce = "20";
console.log("jumpforce: " + jumpforce);
let specialpower = "teleport";
console.log("specialpower: " + specialpower);
let speed = "280";
console.log("speed: " + speed);
let bike = "Honda VFR VTEC";
console.log("bike: " + bike);
let lives = "1";
console.log("lives left: " + lives);
let ammo = "121"
console.log("ammo: " + ammo);
let grenades = "5";
console.log("grenades left: " + grenades);
let energy = "100%";
console.log("energy: " + energy);
let level = "8000";
console.log("level: " + level);
let wanted = "five stars";
console.log("wanted level: " + wanted);